"""
APEX QUANT TRADE LEDGER & PERFORMANCE TRACKER
- Tracks open signals generated by Apex Trading Bot.
- Monitors price ticks every 60s against SL, TP1, and TP2.
- Handles Break-Even trade management on TP1 hit.
- Generates 10:00 PM ICT Daily Performance Summaries.
- Ultra-lightweight JSON database with auto-rotation.
"""

import json
import os
from datetime import datetime, timezone, timedelta
import yfinance as yf

LEDGER_FILE = "trade_ledger.json"

def get_kh_time() -> datetime:
    return datetime.now(timezone(timedelta(hours=7)))

def load_ledger() -> dict:
    if not os.path.exists(LEDGER_FILE):
        return {"trades": [], "last_daily_report": ""}
    try:
        with open(LEDGER_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"trades": [], "last_daily_report": ""}

def save_ledger(data: dict):
    try:
        with open(LEDGER_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    except Exception as e:
        print(f"Error saving ledger: {e}")

def log_new_signal(symbol: str, name: str, emoji: str, direction: str,
                   entry: float, sl: float, tp1: float, tp2: float,
                   conf_pct: int, grade: str, digits: int) -> dict:
    ledger = load_ledger()
    now_kh = get_kh_time()
    now_str = now_kh.strftime("%Y-%m-%d %H:%M:%S")
    date_tag = now_kh.strftime("%m%d")

    # Prevent duplicate logging if an active trade for this symbol exists within the last 3 hours
    for t in ledger.get("trades", []):
        if t["symbol"] == symbol and t["status"] == "OPEN":
            # Check age
            try:
                t_time = datetime.strptime(t["time_opened"], "%Y-%m-%d %H:%M:%S")
                if (now_kh.replace(tzinfo=None) - t_time).total_seconds() < 10800:
                    return t  # Already tracking this setup
            except Exception:
                pass

    count_today = sum(1 for t in ledger.get("trades", []) if t.get("date") == now_kh.strftime("%Y-%m-%d")) + 1
    short_sym = symbol.replace("=F", "").replace("-USD", "").replace("=X", "")
    trade_id = f"#{short_sym}-{date_tag}-{count_today:02d}"

    trade = {
        "id": trade_id,
        "symbol": symbol,
        "name": name,
        "emoji": emoji,
        "direction": direction.upper(),
        "entry": round(entry, digits),
        "sl": round(sl, digits),
        "initial_sl": round(sl, digits),
        "tp1": round(tp1, digits),
        "tp2": round(tp2, digits),
        "digits": digits,
        "conf_pct": conf_pct,
        "grade": grade,
        "status": "OPEN",
        "tp1_hit": False,
        "time_opened": now_str,
        "date": now_kh.strftime("%Y-%m-%d"),
        "close_price": None,
        "close_time": None,
        "pnl_r": 0.0
    }

    ledger.setdefault("trades", []).append(trade)
    save_ledger(ledger)
    print(f"[{now_str}] Logged New Trade: {trade_id} {direction} {name} @ {entry}")
    return trade


def check_open_trades() -> list[str]:
    ledger = load_ledger()
    trades = ledger.get("trades", [])
    open_trades = [t for t in trades if t["status"] == "OPEN"]
    
    if not open_trades:
        return []

    alerts = []
    now_kh = get_kh_time()
    now_str = now_kh.strftime("%H:%M ICT")

    for t in open_trades:
        sym = t["symbol"]
        direction = t["direction"]
        name = t["name"]
        emoji = t["emoji"]
        entry = t["entry"]
        sl = t["sl"]
        tp1 = t["tp1"]
        tp2 = t["tp2"]
        digits = t.get("digits", 2)
        trade_id = t["id"]

        try:
            df = yf.download(sym, period="1d", interval="15m", progress=False)
            if df.empty:
                continue
            df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]
            
            cur = df.iloc[-1]
            high = float(cur["High"])
            low = float(cur["Low"])
            close = float(cur["Close"])

            if direction == "BUY":
                # Check TP2 Hit (Max Target)
                if high >= tp2:
                    t["status"] = "WIN_TP2"
                    t["close_price"] = tp2
                    t["close_time"] = now_str
                    t["pnl_r"] = 2.5
                    alerts.append(
                        f"🎉 <b>TARGET 2 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} BUY\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP2 Hit  :</b> <code>{tp2:,.{digits}f}</code> (+2.5R)\n"
                        f"🏆 <b>Outcome  :</b> FULL WIN (Banked +2.5R Profit) 🚀"
                    )

                # Check TP1 Hit (First Target)
                elif high >= tp1 and not t.get("tp1_hit"):
                    t["tp1_hit"] = True
                    t["sl"] = entry  # Move SL to Break-Even!
                    alerts.append(
                        f"🎯 <b>TARGET 1 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} BUY\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP1 Hit  :</b> <code>{tp1:,.{digits}f}</code> (+1.0R)\n"
                        f"🛡 <b>Action   :</b> Banked 1 Clip. SL moved to Entry (Break-Even)!"
                    )

                # Check SL Hit
                elif low <= sl:
                    if t.get("tp1_hit"):
                        t["status"] = "BE_CLOSED"
                        t["close_price"] = entry
                        t["close_time"] = now_str
                        t["pnl_r"] = 1.0  # Kept the 1R from TP1
                        alerts.append(
                            f"🛡 <b>RUNNER CLOSED AT ENTRY ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"💰 <b>Outcome  :</b> Stopped at Break-Even. Net Profit: +1.0R"
                        )
                    else:
                        t["status"] = "LOSS_SL"
                        t["close_price"] = sl
                        t["close_time"] = now_str
                        t["pnl_r"] = -1.0
                        alerts.append(
                            f"🛑 <b>STOP LOSS HIT ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"{emoji} <b>Asset    :</b> {name} BUY\n"
                            f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                            f"🛑 <b>SL Hit   :</b> <code>{sl:,.{digits}f}</code> (-1.0R)\n"
                            f"💡 <b>Outcome  :</b> Risk managed. Next setup pending."
                        )

            elif direction == "SELL":
                # Check TP2 Hit (Max Target)
                if low <= tp2:
                    t["status"] = "WIN_TP2"
                    t["close_price"] = tp2
                    t["close_time"] = now_str
                    t["pnl_r"] = 2.5
                    alerts.append(
                        f"🎉 <b>TARGET 2 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} SELL\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP2 Hit  :</b> <code>{tp2:,.{digits}f}</code> (+2.5R)\n"
                        f"🏆 <b>Outcome  :</b> FULL WIN (Banked +2.5R Profit) 🚀"
                    )

                # Check TP1 Hit (First Target)
                elif low <= tp1 and not t.get("tp1_hit"):
                    t["tp1_hit"] = True
                    t["sl"] = entry  # Move SL to Break-Even!
                    alerts.append(
                        f"🎯 <b>TARGET 1 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} SELL\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP1 Hit  :</b> <code>{tp1:,.{digits}f}</code> (+1.0R)\n"
                        f"🛡 <b>Action   :</b> Banked 1 Clip. SL moved to Entry (Break-Even)!"
                    )

                # Check SL Hit
                elif high >= sl:
                    if t.get("tp1_hit"):
                        t["status"] = "BE_CLOSED"
                        t["close_price"] = entry
                        t["close_time"] = now_str
                        t["pnl_r"] = 1.0
                        alerts.append(
                            f"🛡 <b>RUNNER CLOSED AT ENTRY ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"💰 <b>Outcome  :</b> Stopped at Break-Even. Net Profit: +1.0R"
                        )
                    else:
                        t["status"] = "LOSS_SL"
                        t["close_price"] = sl
                        t["close_time"] = now_str
                        t["pnl_r"] = -1.0
                        alerts.append(
                            f"🛑 <b>STOP LOSS HIT ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"{emoji} <b>Asset    :</b> {name} SELL\n"
                            f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                            f"🛑 <b>SL Hit   :</b> <code>{sl:,.{digits}f}</code> (-1.0R)\n"
                            f"💡 <b>Outcome  :</b> Risk managed. Next setup pending."
                        )

        except Exception as e:
            print(f"Error checking trade {t.get('id')}: {e}")

    save_ledger(ledger)
    return alerts


def get_active_trades_summary() -> str:
    ledger = load_ledger()
    open_trades = [t for t in ledger.get("trades", []) if t["status"] == "OPEN"]
    if not open_trades:
        return ""

    lines = ["\n📋 <b>ACTIVE SIGNALS TRACKER</b>\n━━━━━━━━━━━━━━━━━━━━━━━━━━"]
    for t in open_trades:
        emoji = t["emoji"]
        short_name = t["name"].split()[0]
        direction = t["direction"]
        entry = t["entry"]
        digits = t.get("digits", 2)
        tp1 = t["tp1"]
        sl = t["sl"]
        be_tag = " [🛡 BE]" if t.get("tp1_hit") else ""
        lines.append(f"{emoji} <b>{short_name} {direction}:</b> <code>{entry:,.{digits}f}</code> ➔ TP1: <code>{tp1:,.{digits}f}</code> | SL: <code>{sl:,.{digits}f}</code>{be_tag}")
    return "\n".join(lines)


def generate_daily_summary() -> str:
    ledger = load_ledger()
    now_kh = get_kh_time()
    today_date = now_kh.strftime("%Y-%m-%d")

    # Get trades from today
    today_trades = [t for t in ledger.get("trades", []) if t.get("date") == today_date]
    if not today_trades:
        # Check last 24h trades if none with exact today tag
        today_trades = ledger.get("trades", [])[-10:] if ledger.get("trades") else []

    total = len(today_trades)
    if total == 0:
        return f"""📊 <b>APEX DAILY PERFORMANCE REPORT</b>
📅 <b>Date:</b> {today_date} | 10:00 PM ICT
━━━━━━━━━━━━━━━━━━━━━━━━━━
⏸ <b>No trade setups triggered today.</b>
💡 <i>Market remained outside high-conviction zones. Capital protected!</i>"""

    wins = sum(1 for t in today_trades if "WIN" in t.get("status", "") or t.get("status") == "BE_CLOSED")
    losses = sum(1 for t in today_trades if t.get("status") == "LOSS_SL")
    open_cnt = sum(1 for t in today_trades if t.get("status") == "OPEN")
    total_closed = wins + losses

    win_rate = (wins / total_closed * 100) if total_closed > 0 else 0
    net_r = sum(t.get("pnl_r", 0.0) for t in today_trades)

    trade_rows = []
    for t in today_trades:
        emoji = t["emoji"]
        short_name = t["name"].split()[0]
        direction = t["direction"]
        entry = t["entry"]
        digits = t.get("digits", 2)
        status = t["status"]
        pnl = t.get("pnl_r", 0.0)

        if "WIN_TP2" in status:
            tag = f"✅ TP2 Hit (+2.5R)"
        elif "BE_CLOSED" in status or status == "WIN_TP1":
            tag = f"✅ TP1 Banked (+1.0R)"
        elif "LOSS" in status:
            tag = f"❌ SL Hit (-1.0R)"
        else:
            tag = f"⏳ Still Open"

        trade_rows.append(f"• {emoji} <b>{short_name} {direction}</b> @ <code>{entry:,.{digits}f}</code> ➔ {tag}")

    trade_list_text = "\n".join(trade_rows)
    pnl_sign = "+" if net_r > 0 else ""

    return f"""📊 <b>APEX DAILY PERFORMANCE REPORT</b>
📅 <b>Date:</b> {today_date} | 10:00 PM ICT
━━━━━━━━━━━━━━━━━━━━━━━━━━
📤 <b>Total Signals :</b> {total}
✅ <b>Wins (TP Hit) :</b> {wins}
❌ <b>Losses (SL)   :</b> {losses}
⏳ <b>Still Active  :</b> {open_cnt}
🎯 <b>Win Rate      :</b> {win_rate:.1f}%
💰 <b>Net P&L (R)   :</b> <b>{pnl_sign}{net_r:.1f}R Profit</b>
━━━━━━━━━━━━━━━━━━━━━━━━━━
<b>TRADE BREAKDOWN:</b>
{trade_list_text}
━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Institutional Accountability | 3-Clip Model</i> 🎯"""
