"""
APEX QUANT TRADE LEDGER & PERFORMANCE TRACKER (V4.0 - MODEL C)
- Tracks open signals generated by Apex Trading Bot with 3-Clip Architecture.
- Monitors price ticks every 60s against SL, TP1 (1.0R), TP2 (2.5R), and TP3 (4.0R Mega-Runner).
- Handles Break-Even trade management on TP1 hit and Mega-Runner trailing.
- Generates 10:00 PM ICT Daily Performance Summaries.
- Ultra-lightweight JSON database with auto-rotation.
"""

import json
import os
from datetime import datetime, timezone, timedelta
import yfinance as yf

LEDGER_FILE = "trade_ledger.json"

def get_kh_time() -> datetime:
    return datetime.now(timezone(timedelta(hours=7)))

def load_ledger() -> dict:
    if not os.path.exists(LEDGER_FILE):
        return {"trades": [], "last_daily_report": ""}
    try:
        with open(LEDGER_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"trades": [], "last_daily_report": ""}

def save_ledger(data: dict):
    try:
        with open(LEDGER_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    except Exception as e:
        print(f"Error saving ledger: {e}")

def log_new_signal(symbol: str, name: str, emoji: str, direction: str,
                   entry: float, sl: float, tp1: float, tp2: float, tp3: float,
                   conf_pct: int, grade: str, digits: int, is_elite: bool = False) -> dict:
    ledger = load_ledger()
    now_kh = get_kh_time()
    now_str = now_kh.strftime("%Y-%m-%d %H:%M:%S")
    date_tag = now_kh.strftime("%m%d")

    # ── GUARDRAIL 1: Hard 3-Hour Cooldown Per Asset ────────────────────────
    # Block ANY trade on this asset within 3 hours, regardless of outcome
    # (Win, Loss, or Still Open). This prevents re-entry traps during
    # pumps/dumps where the bot would keep shorting/buying every 15 minutes.
    for t in ledger.get("trades", []):
        if t["symbol"] == symbol:
            try:
                t_time = datetime.strptime(t["time_opened"], "%Y-%m-%d %H:%M:%S")
                if (now_kh.replace(tzinfo=None) - t_time).total_seconds() < 10800:
                    return t  # Cooldown active — skip this asset entirely
            except Exception:
                pass

    # ── GUARDRAIL 2: Max 2 Active Trades Cap ───────────────────────────────
    # Never have more than 2 simultaneous open signals (margin protection).
    active_count = sum(1 for t in ledger.get("trades", []) if t["status"] == "OPEN")
    if active_count >= 2:
        return None  # At capacity — wait for existing trades to resolve

    # ── GUARDRAIL 3: 2-Loss Circuit Breaker Per Asset ──────────────────────
    # If this asset has 2 consecutive losses in the last 4 hours, freeze it.
    recent_asset_trades = []
    for t in ledger.get("trades", []):
        if t["symbol"] == symbol and t["status"] != "OPEN":
            try:
                t_time = datetime.strptime(t["time_opened"], "%Y-%m-%d %H:%M:%S")
                if (now_kh.replace(tzinfo=None) - t_time).total_seconds() < 14400:  # 4 hours
                    recent_asset_trades.append(t)
            except Exception:
                pass
    if len(recent_asset_trades) >= 2:
        last_two = sorted(recent_asset_trades, key=lambda x: x["time_opened"])[-2:]
        if all(t.get("pnl_r", 0) < 0 for t in last_two):
            return None  # Circuit breaker triggered — asset frozen

    count_today = sum(1 for t in ledger.get("trades", []) if t.get("date") == now_kh.strftime("%Y-%m-%d")) + 1
    short_sym = symbol.replace("=F", "").replace("-USD", "").replace("=X", "")
    trade_id = f"#{short_sym}-{date_tag}-{count_today:02d}"

    trade = {
        "id": trade_id,
        "symbol": symbol,
        "name": name,
        "emoji": emoji,
        "direction": direction.upper(),
        "entry": round(entry, digits),
        "sl": round(sl, digits),
        "initial_sl": round(sl, digits),
        "tp1": round(tp1, digits),
        "tp2": round(tp2, digits),
        "tp3": round(tp3, digits),
        "digits": digits,
        "conf_pct": conf_pct,
        "grade": grade,
        "is_elite": is_elite,
        "status": "OPEN",
        "tp1_hit": False,
        "tp2_hit": False,
        "time_opened": now_str,
        "date": now_kh.strftime("%Y-%m-%d"),
        "close_price": None,
        "close_time": None,
        "pnl_r": 0.0
    }

    ledger.setdefault("trades", []).append(trade)
    save_ledger(ledger)
    print(f"[{now_str}] Logged New Trade: {trade_id} {direction} {name} @ {entry} (TP1:{tp1}, TP2:{tp2}, TP3:{tp3})")
    return trade


def check_open_trades() -> list[str]:
    ledger = load_ledger()
    trades = ledger.get("trades", [])
    open_trades = [t for t in trades if t["status"] == "OPEN"]
    
    if not open_trades:
        return []

    alerts = []
    now_kh = get_kh_time()
    now_str = now_kh.strftime("%H:%M ICT")

    for t in open_trades:
        sym = t["symbol"]
        direction = t["direction"]
        name = t["name"]
        emoji = t["emoji"]
        entry = t["entry"]
        sl = t["sl"]
        tp1 = t["tp1"]
        tp2 = t["tp2"]
        tp3 = t.get("tp3", tp2)
        digits = t.get("digits", 2)
        trade_id = t["id"]
        weight = 1.5 if t.get("is_elite") else 1.0

        try:
            df = yf.download(sym, period="1d", interval="15m", progress=False)
            if df.empty:
                continue
            df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]
            
            cur = df.iloc[-1]
            high = float(cur["High"])
            low = float(cur["Low"])
            close = float(cur["Close"])

            if direction == "BUY":
                # Check TP3 Hit (Mega-Runner Target)
                if high >= tp3:
                    t["status"] = "WIN_TP3"
                    t["close_price"] = tp3
                    t["close_time"] = now_str
                    t["pnl_r"] = 4.0 * weight
                    alerts.append(
                        f"🚀 <b>MEGA-RUNNER TP3 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} BUY\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🚀 <b>TP3 Hit  :</b> <code>{tp3:,.{digits}f}</code> (+4.0R)\n"
                        f"🏆 <b>Outcome  :</b> MEGA-RUNNER MAXIMUM WIN (+4.0R Profit) 🚀🔥"
                    )

                # Check TP2 Hit (Standard Target)
                elif high >= tp2 and not t.get("tp2_hit"):
                    t["tp2_hit"] = True
                    alerts.append(
                        f"🎉 <b>TARGET 2 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} BUY\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP2 Hit  :</b> <code>{tp2:,.{digits}f}</code> (+2.5R)\n"
                        f"🚀 <b>Action   :</b> Banked 2nd Clip! Runner riding to TP3 (4.0R)..."
                    )

                # Check TP1 Hit (First Target)
                elif high >= tp1 and not t.get("tp1_hit"):
                    t["tp1_hit"] = True
                    t["sl"] = entry  # Move SL to Break-Even!
                    alerts.append(
                        f"🎯 <b>TARGET 1 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} BUY\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP1 Hit  :</b> <code>{tp1:,.{digits}f}</code> (+1.0R)\n"
                        f"🛡 <b>Action   :</b> Banked 1 Clip. SL moved to Entry (Risk = $0.00)!"
                    )

                # Check SL Hit
                elif low <= sl:
                    if t.get("tp2_hit"):
                        t["status"] = "WIN_TP2"
                        t["close_price"] = entry
                        t["close_time"] = now_str
                        t["pnl_r"] = 2.5 * weight
                        alerts.append(
                            f"🛡 <b>RUNNER CLOSED ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"💰 <b>Outcome  :</b> Closed at BE after TP2. Net Profit: +2.5R"
                        )
                    elif t.get("tp1_hit"):
                        t["status"] = "BE_CLOSED"
                        t["close_price"] = entry
                        t["close_time"] = now_str
                        t["pnl_r"] = 1.0 * weight
                        alerts.append(
                            f"🛡 <b>RUNNER CLOSED AT ENTRY ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"💰 <b>Outcome  :</b> Stopped at Break-Even. Net Profit: +1.0R"
                        )
                    else:
                        t["status"] = "LOSS_SL"
                        t["close_price"] = sl
                        t["close_time"] = now_str
                        t["pnl_r"] = -1.0 * weight
                        alerts.append(
                            f"🛑 <b>STOP LOSS HIT ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"{emoji} <b>Asset    :</b> {name} BUY\n"
                            f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                            f"🛑 <b>SL Hit   :</b> <code>{sl:,.{digits}f}</code> (-1.0R)\n"
                            f"💡 <b>Outcome  :</b> Risk managed. Next setup pending."
                        )

            elif direction == "SELL":
                # Check TP3 Hit (Mega-Runner Target)
                if low <= tp3:
                    t["status"] = "WIN_TP3"
                    t["close_price"] = tp3
                    t["close_time"] = now_str
                    t["pnl_r"] = 4.0 * weight
                    alerts.append(
                        f"🚀 <b>MEGA-RUNNER TP3 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} SELL\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🚀 <b>TP3 Hit  :</b> <code>{tp3:,.{digits}f}</code> (+4.0R)\n"
                        f"🏆 <b>Outcome  :</b> MEGA-RUNNER MAXIMUM WIN (+4.0R Profit) 🚀🔥"
                    )

                # Check TP2 Hit (Standard Target)
                elif low <= tp2 and not t.get("tp2_hit"):
                    t["tp2_hit"] = True
                    alerts.append(
                        f"🎉 <b>TARGET 2 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} SELL\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP2 Hit  :</b> <code>{tp2:,.{digits}f}</code> (+2.5R)\n"
                        f"🚀 <b>Action   :</b> Banked 2nd Clip! Runner riding to TP3 (4.0R)..."
                    )

                # Check TP1 Hit (First Target)
                elif low <= tp1 and not t.get("tp1_hit"):
                    t["tp1_hit"] = True
                    t["sl"] = entry  # Move SL to Break-Even!
                    alerts.append(
                        f"🎯 <b>TARGET 1 HIT! ({name})</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                        f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                        f"{emoji} <b>Asset    :</b> {name} SELL\n"
                        f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                        f"🎯 <b>TP1 Hit  :</b> <code>{tp1:,.{digits}f}</code> (+1.0R)\n"
                        f"🛡 <b>Action   :</b> Banked 1 Clip. SL moved to Entry (Risk = $0.00)!"
                    )

                # Check SL Hit
                elif high >= sl:
                    if t.get("tp2_hit"):
                        t["status"] = "WIN_TP2"
                        t["close_price"] = entry
                        t["close_time"] = now_str
                        t["pnl_r"] = 2.5 * weight
                        alerts.append(
                            f"🛡 <b>RUNNER CLOSED ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"💰 <b>Outcome  :</b> Closed at BE after TP2. Net Profit: +2.5R"
                        )
                    elif t.get("tp1_hit"):
                        t["status"] = "BE_CLOSED"
                        t["close_price"] = entry
                        t["close_time"] = now_str
                        t["pnl_r"] = 1.0 * weight
                        alerts.append(
                            f"🛡 <b>RUNNER CLOSED AT ENTRY ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"💰 <b>Outcome  :</b> Stopped at Break-Even. Net Profit: +1.0R"
                        )
                    else:
                        t["status"] = "LOSS_SL"
                        t["close_price"] = sl
                        t["close_time"] = now_str
                        t["pnl_r"] = -1.0 * weight
                        alerts.append(
                            f"🛑 <b>STOP LOSS HIT ({name})</b>\n"
                            f"━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                            f"🏷 <b>Trade ID :</b> <code>{trade_id}</code>\n"
                            f"{emoji} <b>Asset    :</b> {name} SELL\n"
                            f"💰 <b>Entry    :</b> <code>{entry:,.{digits}f}</code>\n"
                            f"🛑 <b>SL Hit   :</b> <code>{sl:,.{digits}f}</code> (-1.0R)\n"
                            f"💡 <b>Outcome  :</b> Risk managed. Next setup pending."
                        )

        except Exception as e:
            print(f"Error checking trade {t.get('id')}: {e}")

    save_ledger(ledger)
    return alerts


def get_active_trades_summary() -> str:
    ledger = load_ledger()
    open_trades = [t for t in ledger.get("trades", []) if t["status"] == "OPEN"]
    if not open_trades:
        return ""

    lines = ["\n📋 <b>ACTIVE SIGNALS TRACKER</b>\n━━━━━━━━━━━━━━━━━━━━━━━━━━"]
    for t in open_trades:
        emoji = t["emoji"]
        short_name = t["name"].split()[0]
        direction = t["direction"]
        entry = t["entry"]
        digits = t.get("digits", 2)
        tp1 = t["tp1"]
        tp2 = t.get("tp2", tp1)
        tp3 = t.get("tp3", tp2)
        sl = t["sl"]
        be_tag = " [🛡 BE]" if t.get("tp1_hit") else ""
        lines.append(f"{emoji} <b>{short_name} {direction}:</b> <code>{entry:,.{digits}f}</code> ➔ TP1:<code>{tp1:,.{digits}f}</code> | TP2:<code>{tp2:,.{digits}f}</code> | TP3:<code>{tp3:,.{digits}f}</code>{be_tag}")
    return "\n".join(lines)


def generate_daily_summary() -> str:
    ledger = load_ledger()
    now_kh = get_kh_time()
    today_date = now_kh.strftime("%Y-%m-%d")

    # Get trades from today
    today_trades = [t for t in ledger.get("trades", []) if t.get("date") == today_date]
    if not today_trades:
        # Check last 24h trades if none with exact today tag
        today_trades = ledger.get("trades", [])[-10:] if ledger.get("trades") else []

    total = len(today_trades)
    if total == 0:
        return f"""📊 <b>APEX DAILY PERFORMANCE REPORT</b>
📅 <b>Date:</b> {today_date} | 10:00 PM ICT
━━━━━━━━━━━━━━━━━━━━━━━━━━
⏸ <b>No trade setups triggered today.</b>
💡 <i>Market remained outside high-conviction zones. Capital protected!</i>"""

    wins = sum(1 for t in today_trades if "WIN" in t.get("status", "") or t.get("status") == "BE_CLOSED")
    losses = sum(1 for t in today_trades if t.get("status") == "LOSS_SL")
    open_cnt = sum(1 for t in today_trades if t.get("status") == "OPEN")
    total_closed = wins + losses

    win_rate = (wins / total_closed * 100) if total_closed > 0 else 0
    net_r = sum(t.get("pnl_r", 0.0) for t in today_trades)

    trade_rows = []
    for t in today_trades:
        emoji = t["emoji"]
        short_name = t["name"].split()[0]
        direction = t["direction"]
        entry = t["entry"]
        digits = t.get("digits", 2)
        status = t["status"]
        pnl = t.get("pnl_r", 0.0)

        if "WIN_TP2" in status:
            tag = f"✅ TP2 Hit (+2.5R)"
        elif "BE_CLOSED" in status or status == "WIN_TP1":
            tag = f"✅ TP1 Banked (+1.0R)"
        elif "LOSS" in status:
            tag = f"❌ SL Hit (-1.0R)"
        else:
            tag = f"⏳ Still Open"

        trade_rows.append(f"• {emoji} <b>{short_name} {direction}</b> @ <code>{entry:,.{digits}f}</code> ➔ {tag}")

    trade_list_text = "\n".join(trade_rows)
    pnl_sign = "+" if net_r > 0 else ""

    return f"""📊 <b>APEX DAILY PERFORMANCE REPORT</b>
📅 <b>Date:</b> {today_date} | 10:00 PM ICT
━━━━━━━━━━━━━━━━━━━━━━━━━━
📤 <b>Total Signals :</b> {total}
✅ <b>Wins (TP Hit) :</b> {wins}
❌ <b>Losses (SL)   :</b> {losses}
⏳ <b>Still Active  :</b> {open_cnt}
🎯 <b>Win Rate      :</b> {win_rate:.1f}%
💰 <b>Net P&L (R)   :</b> <b>{pnl_sign}{net_r:.1f}R Profit</b>
━━━━━━━━━━━━━━━━━━━━━━━━━━
<b>TRADE BREAKDOWN:</b>
{trade_list_text}
━━━━━━━━━━━━━━━━━━━━━━━━━━
<i>Institutional Accountability | 3-Clip Model</i> 🎯"""


def get_todays_signals_view() -> str:
    ledger = load_ledger()
    now_kh = get_kh_time()
    today_date = now_kh.strftime("%Y-%m-%d")
    now_str = now_kh.strftime("%H:%M:%S ICT")

    # Get trades from today or last 10
    today_trades = [t for t in ledger.get("trades", []) if t.get("date") == today_date]
    if not today_trades:
        today_trades = ledger.get("trades", [])[-10:] if ledger.get("trades") else []

    if not today_trades:
        return f"""📜 <b>TODAY'S SIGNALS LEDGER</b> ({now_str})
━━━━━━━━━━━━━━━━━━━━━━━━━━
⏸ <b>No signals logged yet today.</b>
💡 <i>Tap '🔄 Refresh Scan' to analyze live markets!</i>"""

    rows = []
    total_r = 0.0
    wins = 0
    losses = 0

    for i, t in enumerate(today_trades, 1):
        emoji = t.get("emoji", "🎯")
        name = t.get("name", "Asset")
        short_name = name.split()[0]
        direction = t.get("direction", "BUY")
        entry = t.get("entry", 0.0)
        digits = t.get("digits", 2)
        status = t.get("status", "OPEN")
        tp1 = t.get("tp1", 0.0)
        sl = t.get("sl", 0.0)
        time_str = t.get("time_opened", "")[-8:-3] if t.get("time_opened") else ""

        if "WIN_TP2" in status:
            tag = f"✅ <b>TP2 HIT (+2.5R)</b>"
            total_r += 2.5
            wins += 1
        elif "BE_CLOSED" in status or status == "WIN_TP1":
            tag = f"✅ <b>TP1 BANKED (+1.0R)</b>"
            total_r += 1.0
            wins += 1
        elif "LOSS" in status:
            tag = f"❌ <b>SL HIT (-1.0R)</b>"
            total_r -= 1.0
            losses += 1
        else:
            be_tag = " [🛡 BE]" if t.get("tp1_hit") else ""
            tag = f"⏳ <b>STILL OPEN</b> (TP1: <code>{tp1:,.{digits}f}</code> | SL: <code>{sl:,.{digits}f}</code>{be_tag})"

        time_tag = f" ({time_str})" if time_str else ""
        rows.append(f"{i}. {emoji} <b>{short_name} {direction}</b> @ <code>{entry:,.{digits}f}</code>{time_tag}\n   ➔ {tag}")

    trades_text = "\n\n".join(rows)
    pnl_sign = "+" if total_r > 0 else ""

    return f"""📜 <b>TODAY'S SIGNALS LEDGER</b> ({now_str})
━━━━━━━━━━━━━━━━━━━━━━━━━━
{trades_text}
━━━━━━━━━━━━━━━━━━━━━━━━━━
💰 <b>Running Score:</b> {wins}W - {losses}L (<b>{pnl_sign}{total_r:.1f}R Profit</b>)
<i>Tap '🔄 Refresh Scan' to return to Market Radar</i> 🎯"""

